version: '3'

volumes:
  db-data:

services:
  db:
    image: postgres:14
    container_name: blog-db
    volumes:
      - db-data:/var/lib/postgresql/blog_db_development/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
